import React, { useState } from 'react';
import { Flame, Mail, Lock, Loader2, AlertTriangle } from 'lucide-react';
import { authClient } from '../services/auth.client';

interface AuthPageProps {
  onLoginSuccess: () => void;
}

export const AuthPage: React.FC<AuthPageProps> = ({ onLoginSuccess }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !password) {
      setError('Please enter both email and password.');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await authClient.signIn.email({
        email,
        password,
      });

      if (response.error) {
        setError(response.error.message || 'Invalid email or password.');
      } else {
        onLoginSuccess();
      }
    } catch (err: any) {
      console.error('Sign-in error:', err);
      setError('A connection error occurred. Please verify backend is running.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-viewport">
      <div className="auth-background-glow" />
      <div className="glass-card auth-card">
        {/* Logo */}
        <div className="auth-logo-group">
          <div className="brand-logo-glow" aria-hidden="true" style={{ margin: '0 auto 1rem auto', width: '3rem', height: '3rem' }}>
            <Flame size={28} color="#ffffff" />
          </div>
          <h1 className="brand-title" style={{ fontSize: '2rem', textAlign: 'center' }}>AeroSent</h1>
          <p className="brand-subtitle" style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
            Aviation Sentiment Intelligence
          </p>
        </div>

        {/* Info Box */}
        <div className="auth-info-box">
          <p style={{ margin: 0, fontSize: '0.78rem', color: 'var(--color-text-muted)', lineHeight: '1.4' }}>
            <strong>System Notice:</strong> Signups are currently disabled. Please authenticate using the credentials generated by the database seeding script.
          </p>
        </div>

        {/* Error Alert */}
        {error && (
          <div className="glass-card dg-result-banner dg-result-error" style={{ padding: '0.75rem 1rem', marginBottom: '1.25rem' }} role="alert">
            <AlertTriangle size={18} className="dg-result-icon" />
            <div>
              <p className="dg-result-title" style={{ fontSize: '0.85rem' }}>Authentication Error</p>
              <p className="dg-result-subtitle" style={{ fontSize: '0.75rem' }}>{error}</p>
            </div>
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit} className="auth-form">
          <div className="filter-group" style={{ marginBottom: '1.25rem' }}>
            <label htmlFor="auth-email" className="filter-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.5rem' }}>
              <Mail size={13} /> Email Address
            </label>
            <input
              id="auth-email"
              type="email"
              className="filter-input"
              style={{ width: '100%' }}
              placeholder="name@aerosent.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              disabled={loading}
            />
          </div>

          <div className="filter-group" style={{ marginBottom: '1.75rem' }}>
            <label htmlFor="auth-password" className="filter-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.5rem' }}>
              <Lock size={13} /> Password
            </label>
            <input
              id="auth-password"
              type="password"
              className="filter-input"
              style={{ width: '100%' }}
              placeholder="••••••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              disabled={loading}
            />
          </div>

          <button
            type="submit"
            className="dg-btn dg-btn-primary"
            style={{ width: '100%', justifyContent: 'center', padding: '0.8rem' }}
            disabled={loading}
          >
            {loading ? (
              <>
                <Loader2 size={16} className="playground-spinner" />
                Signing In…
              </>
            ) : (
              'Sign In to Dashboard'
            )}
          </button>
        </form>
      </div>
    </div>
  );
};
